spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-info-loan-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user-info-loan-service/**
          filters:
            - StripPrefix=2
        - id: loan-calc-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/loan-calc-service/**
          filters:
            - StripPrefix=2

server:
  port: 8081